spring:
  application:
    name: ipo-insight-plus-api
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ipo-insight-plus
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${IPOINSIGHTPLUS_EMAIL_USERNAME}
    password: ${IPOINSIGHTPLUS_EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
            auth: true
            starttls:
              enable: true
            ssl:
              protocols: TLSv1.2
logging:
  file:
    name: logs/ipo-insight-plus-api.log

ipo-insight-plus:
    api:
      url: https://www.sharesansar.com/existing-issues
    notification:
      from:
        email: ${IPOINSIGHTPLUS_EMAIL_USERNAME}
        name: IPO Insight+
      subject:
        new-ipo: 🚨 Here We Go! New IPO
        closing-ipo: 📌 IPO Closure Alert
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 86400000
    rate-limiting:
      max-requests: 5
      token: 5
      duration-minutes: 1